# Generated by Django 2.2.13 on 2020-09-23 15:39

from django.db import migrations



def remove_vendors_pss(apps, scheme_editor):
    
    model = apps.get_model('vendors', 'poolmembership')
    model.objects.filter(string__contains='PSS').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0040_auto_20181114_1525'),
    ]

    operations = [
    	migrations.RunPython(remove_vendors_pss)
    ]
